{
    "docs": "https://docs.ansible.com/ansible-core/2.16/dev_guide/testing/sanity/pep8.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test pep8` [[explain](https://docs.ansible.com/ansible-core/2.16/dev_guide/testing/sanity/pep8.html)] failed with 1 error:", 
            "output": "plugins/action/services.py:47:17: E127: continuation line over-indented for visual indent"
        }
    ], 
    "verified": false
}
